apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30003 # Если хотите указать фиксированный nodePort
  selector:
    project: {{ .Release.Name }}
